/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EX02;

// Define a class named "App"
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    // Instance variables
    String name;
    int model;

    // Constructor
    public App(String name, int age) {
        this.name = name;
        this.model = age;
    }

    // Method to display information about the person
    public void displayInfo() {
        System.out.println("Name: " + name);
        System.out.println("Age: " + model);
    }   

    public static void main(String[] args) {
        
        // Create two Person objects
        App app1 = new App("iPhone", 14);
        App app2 = new App("SamSung Galaxy", 7);

        // Access and modify object properties
        app1.model = 5;

        // Call object methods
        app1.displayInfo();
        app2.displayInfo();
    }

}
