/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EX01;

import java.awt.Graphics;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class App extends Frame {
    public void paint(Graphics g) {
        g.drawLine(20, 100, 120, 100);
    }
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App frame = new App();
        frame.setSize(300, 200);
        frame.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                System.exit(0);
            }
        });
        frame.setVisible(true);
               
        System.out.println(new App().getGreeting());
    }
}
