/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package B11155001;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App b=new App();
        b.getGreeting();
        System.out.println(new App().getGreeting());
        Student d=new Student();
        d.setStudentInformation("Aaron", "B11155001");
        System.out.println(d.getStudentname()+" "+d.getStudentid());
        Student e=new Student();
        e.setStudentInformation("Mary", "B11155002");
        d.askname(e);
        System.out.println(d.askname(e));
    }
    
}
