/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package B11155001Ax;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        System.out.println("矩陣 A 的列(p) 與 行(q) ");
        int p = 5; //System.out.println();
        System.out.print("p= "+p+",   ");
        int q = 5;  //System.out.println();
        System.out.print("q= "+q);
        
        System.out.println("矩陣 A 如下 ");

        AX a=new AX();      // AX a    : 宣告物件
                            // new AX(): 生成物件
        a.blockprint(p,q);
    }
}
